[project]
name = "20250125-ai-x-finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alpaca-trade-api>=3.2.0",
    "polygon-api-client>=1.14.3",
    "praw>=7.8.1",
    "yfinance>=0.2.52",
]

[dependency-groups]
dev = [
    "ipython>=8.31.0",
]
